import oracledb
import csv
import os

# Configura conexão (substitua pelos seus dados)
try:
    conn = oracledb.connect(
        user="rm562225",
        password="fiap25",
        dsn="oracle.fiap.com.br:1521/ORCL"
    )
    cursor = conn.cursor()
except Exception as e:
    print(f"❌ Erro ao conectar ao banco: {e}")
    exit(1)

# Criação da tabela (caso não exista)
try:
    cursor.execute("""
    BEGIN
        EXECUTE IMMEDIATE '
        CREATE TABLE sensores_irrigacao (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fosforo_presente NUMBER(1),
            potassio_presente NUMBER(1),
            ph_simulado NUMBER(5,2),
            umidade NUMBER(5,2),
            irrigacao_ativa NUMBER(1),
            data_insercao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN RAISE; END IF;
    END;
    """)
    conn.commit()
except Exception as e:
    print(f"❌ Erro ao criar tabela (se não existir): {e}")

def inserir_dados(fosforo, potassio, ph, umidade, irrigacao):
    try:
        cursor.execute("""
            INSERT INTO sensores_irrigacao (
                fosforo_presente, potassio_presente, ph_simulado, umidade, irrigacao_ativa
            ) VALUES (:1, :2, :3, :4, :5)
        """, (fosforo, potassio, ph, umidade, irrigacao))
        conn.commit()
        print("✅ Dados inseridos com sucesso.")
    except Exception as e:
        print(f"❌ Erro ao inserir dados: {e}")

def consultar_dados():
    try:
        cursor.execute("SELECT * FROM sensores_irrigacao ORDER BY data_insercao DESC")
        registros = cursor.fetchall()
        print("\n--- DADOS ARMAZENADOS ---")
        for r in registros:
            print(r)
    except Exception as e:
        print(f"❌ Erro ao consultar dados: {e}")

def atualizar_umidade(id_registro, nova_umidade):
    try:
        cursor.execute("""
            UPDATE sensores_irrigacao
            SET umidade = :1
            WHERE id = :2
        """, (nova_umidade, id_registro))
        conn.commit()
        print("✅ Registro atualizado.")
    except Exception as e:
        print(f"❌ Erro ao atualizar registro: {e}")

def deletar_registro(id_registro):
    try:
        cursor.execute("DELETE FROM sensores_irrigacao WHERE id = :1", (id_registro,))
        conn.commit()
        print("🗑️ Registro removido.")
    except Exception as e:
        print(f"❌ Erro ao deletar registro: {e}")

def exportar_csv():
    try:
        cursor.execute("SELECT * FROM sensores_irrigacao ORDER BY data_insercao DESC")
        caminho = os.path.abspath('dados_irrigacao.csv')
        with open('dados_irrigacao.csv', mode='w', newline='') as arquivo_csv:
            escritor_csv = csv.writer(arquivo_csv)
            colunas = [desc[0] for desc in cursor.description]
            escritor_csv.writerow(colunas)
            for linha in cursor:
                escritor_csv.writerow(linha)
        print(f"✅ Dados exportados para '{caminho}' com sucesso!")
    except Exception as e:
        print(f"❌ Erro ao exportar CSV: {e}")

def menu():
    while True:
        print("\n--- SISTEMA DE IRRIGAÇÃO INTELIGENTE ---")
        print("1. Inserir novo dado (manual)")
        print("2. Consultar dados")
        print("3. Atualizar umidade")
        print("4. Deletar registro")
        print("5. Exportar dados para CSV")
        print("6. Sair")
        opcao = input("Escolha uma opção: ")

        if opcao == "1":
            try:
                fosforo = int(input("Fósforo presente (1 = Sim, 0 = Não): "))
                potassio = int(input("Potássio presente (1 = Sim, 0 = Não): "))
                ph = float(input("pH simulado (0 a 14): "))
                umidade = float(input("Umidade (%): "))
                irrigacao = int(input("Irrigação ativa (1 = Sim, 0 = Não): "))
                inserir_dados(fosforo, potassio, ph, umidade, irrigacao)
            except ValueError:
                print("❌ Entrada inválida, por favor digite números corretos.")
        elif opcao == "2":
            consultar_dados()
        elif opcao == "3":
            try:
                id_registro = int(input("ID do registro a atualizar: "))
                nova_umidade = float(input("Nova umidade (%): "))
                atualizar_umidade(id_registro, nova_umidade)
            except ValueError:
                print("❌ Entrada inválida, digite números corretos.")
        elif opcao == "4":
            try:
                id_registro = int(input("ID do registro a deletar: "))
                deletar_registro(id_registro)
            except ValueError:
                print("❌ Entrada inválida, digite um número inteiro.")
        elif opcao == "5":
            exportar_csv()
        elif opcao == "6":
            print("Saindo... Até mais!")
            break
        else:
            print("❌ Opção inválida.")

try:
    menu()
finally:
    cursor.close()
    conn.close()
